defaults:
  - default
  - _self_

draft_model: null
gamma: 5
ensemble: identity
alpha: 0.0

spec:
    model: ${path_join:${oc.env:MODEL_PATH},${..draft_model}}
    num_speculative_tokens: ${..gamma}

llm:
  model: ${path_join:${oc.env:MODEL_PATH},${..model}}
